server:
  port: 2003

spring:
  application:
    name: seata-account-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: yy1314yy

  main:
    allow-circular-references: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
