server:
  port: 8004
spring:
  application:
    name: cloud-provide-payment

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据元操作类型
#    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql 驱动包
#    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSl=false
#    username: root
#    password: yy1314yy

  cloud:
    zookeeper:
      connect-string: 192.168.88.100:2181
