server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.100:3333
        # server-addr: 127.0.0.1:8848 # 配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
