server:
  port: 83
spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 消费者将要去访问的微服务名称
service-uri:
  nacos-user-server: http://nacos-payment-provider
