server:
  port: 80

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true

#ribbon:
#  ReadTimeout: 1000
#  ConnectTimeout: 1000

# 设置Feign客户端所用的时间
feign:
  client:
    config:
      default:
        # 指的是连接所用的时间，适用于网络状况正常情况下，两端连接所用的时间
        connect-timeout: 5000
        # 指的是建立连接后从服务器读取到可用资源所用的时间
        read-timeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
